### ISSUE TITLE
Bulk Actions on Tickets

### ISSUE THREAD

**Issue by oybi** [dtbaker/ucm#3]
Using bulk actions to change status of a ticket to resolved, doesn't work.

**Comment by dtbaker** [comment]
Seems ok here, be sure the tick box is checked next to the resolved select box

Step 1:

![image](https://user-images.githubusercontent.com/543073/40975425-41dc81ea-690e-11e8-86b1-254f89371593.png)


Step 2:

![image](https://user-images.githubusercontent.com/543073/40975428-45a45456-690e-11e8-99e2-cf9716fbbcab.png)

**Comment by oybi** [comment]
Dave,

I just tested again. It isn't working.

**Comment by oybi** [comment]
@dtbaker Can you reopen this issue please?

**Comment by oybi** [comment]
@dtbaker I lied. It does work. It just doesn't refresh the page, so it appears that they are still there. Thanks.

**Comment by dtbaker** [comment]
@oybi jump into Settings > Advanced and change the `cache_enabled` value from 1 to 0 if it is causing issues
