### ISSUE TITLE
New Supplier Group Defaults to Customer, Groups Missing in Supplier

### ISSUE THREAD

**Issue by MojoCreator** [dtbaker/ucm#4]
I have three versions of this software installed and every version acts the same. Two different servers and PHP setups show the same response.

1. After making a new supplier (https://www.screencast.com/t/rzxjqpBJ) and (https://www.screencast.com/t/X6TuVgGrN7wG) I am not given the supplier groups that apply to Supplier. I went to Settings > Groups and all Groups are "Available to" customer as default even though I made the group in the Supplier screen (https://www.screencast.com/t/SEsGIAZxD)

2. Next, I went to the db table under group > owner_table and changed customer to supplier but that didn't fix the issue. (https://www.screencast.com/t/qZNex6V1C)

3. I went to the details of the supplier and none of the supplier groups show up, the only groups that show up are the customer groups even though I am not editing a customer (https://www.screencast.com/t/jRlt7yCr)

4. I can't edit the group in the backend either - https://www.screencast.com/t/mMOu3hyWcF

I can't figure out what the problem is. I have opened a ticket but have not received any type of response. Any help would be greatly appreciated.

**Comment by dtbaker** [comment]
Hi @MojoCreator thank you SO much for such a detailed report.

Right now the "Groups" are shared between all Customer Types (e.g. Lead, Supplier, Customer, or any other "types" you create in the settings area). This allows for an entity to transition between customer types easily (e.g. from a Lead to a Customer) without loosing their associated groups.

If you would like to change this function and keep a separate list of groups, please upgrade to the latest version and change the advanced variable `groups_unique_per_customer_type` from `0` to `1`.

After that change you will have unique groups per customer type:

![image](https://user-images.githubusercontent.com/543073/40975994-0a75726e-6910-11e8-9d1d-79ce7ad4a3cd.png)
